version: "3"

services:
  # Wordpress
  wordpress:
    image: wordpress:latest
    ports:
      - "3005:80"
    restart: always
    volumes: ["./:/var/www/html"]
    environment:
      WORDPRESS_DB_HOST: host.docker.internal:3306 #Sample
      WORDPRESS_DB_USER: root #Sample
      WORDPRESS_DB_PASSWORD: 12345678 #Sample
      WORDPRESS_DB_NAME: wordpress #Sample
